CREATE TABLE IF NOT EXISTS `orders` (
`id` INT (11) NOT NULL AUTO_INCREMENT,
`user_id` INT (11) NOT NULL,
`date_created` datetime NOT NULL,
`date_payment` datetime DEFAULT NULL,
`date_modification` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`status` TINYINT(4) NOT NULL DEFAULT '0',
`comment` TEXT NOT NULL,
`user_ip` VARCHAR(15) NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=MYISAM DEFAULT CHARSET=UTF8;